### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by hrvylein** [wlbr/feiertage#2]
No issue, but I would like to thank you for this class!

**Comment by mpetavy** [comment]
Me too, thank you very much!
One little issue : in Bayern "MariäHimmerlfahrt" is missing as as Feiertag :-)
Thanks again!

**Comment by wlbr** [comment]
Hey, thanks a lot! I really appreciate the feedback of all of you! I feel honored.

The problem with MariäHimmerlfahrt in Bayern is, that it is not a public holiday in all parts of Bavaria. Only the catholic parts have this additonal day off.

What would be the best way to handle issues like this one?
If the answer is: it is a holiday for as long as it is a partial holiday throuout the country, then how do we handle the "Augsburger Hohes Friedensfest"?

**Comment by wlbr** [comment]
I think the problem of local (really local as parts of a "Bundesland" or even a city) holidays is not really solvable by the library. You would need to maintain a list of subregions. A caller would need to pass a location and the lib would need to map that to a (sub)region. 
While this is possible it is beyond the intention of this standalone library. 

Feel free to fork and extend!
