### ISSUE TITLE
How to compile just the command line program?

### ISSUE THREAD

**Issue by tastytea** [wlbr/feiertage#4]
Could you add info on how to compile if I just want the commandline program and don't know anything about go? I append my solution but it looks odd to me. :-)

```
mkdir -p src/github.com/wlbr
cd src/github.com/wlbr
ln -s ../../../ feiertage
cd -
GOPATH="${PWD}" make buildcmd
```

**Comment by wlbr** [comment]
Did you check the releases page? It is propably the easiest way to simply take one of those binaries fitting to your platform.
https://github.com/wlbr/feiertage/releases

Would you need a different OS/architecture?

**Comment by tastytea** [comment]
Oops, hadn't seen those. Thanks!
