### ISSUE TITLE
Feiertag.Time has not the correct timeZone

### ISSUE THREAD

**Issue by leberKleber** [wlbr/feiertage#6]
The given Feirtage.Time values are UTC but I expect 'Europe/Berlin' or other CET time

**Comment by wlbr** [comment]
Well, one could argue, what the correct timezone should be, if not UTC.
Or, if a timezone for a day, not a point of time, is important or not.

Anyway: you will find the new function feiertage.SetDefaultTimeZone to change the timezone to the one you prefer.
Note: the timezone is set on package level and "stored" in the Feiertag during the creation time of the Feiertag object. So every Feiertag created after the call of feiertage.SetDefaultTimeZone will use that timezone. Feiertage create before the call to feiertage.SetDefaultTimeZone will not change their timezone.
feiertage.SetDefaultTimeZone can be called multiple times using different timezones.

The solution using the package level setting may not be nice, but is needed to keep the change backward compatible.
